version: '3.8'
services:
  back:
    build:
      context: "./backend"
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    networks:
      - deploy # 컨테이너를 연결할 네트워크 

networks:
  deploy: # 네트워크 정의
    external: true
