#server:
#  port: 8080
#  servlet:
#    context-path: /api/v1
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mariadb://localhost:3306/nocolored_database?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    generate-ddl: true
#    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
      ddl-auto: update

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
#  profiles:
#    active: local
#    include: jwt
#
#file:
#  upload:
#    directory: /tmp/local/data/
#
#
